name: CI

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: ğŸ install dependencies
        run: |
          pip install norminette

      - name: ğŸ§ª run test
        run: |
          norminette || exit 1

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update master branch
        uses: julb/action-manage-branch@v1
        with:
          name: master
          state: present
          from: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/checkout@v2
      #   with:
      #     ref: master

      # - name: clean
      #   run: |
      #     rm -rf ./**/*.{txt,out,md}
      #     rm -rf ./**/*/{LICENSE.*, README.*}
      #     rm -rf ./**/*/{LICENSE, README}

      # - name: ğŸš€ deploy
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "ci: :rocket: deploy assignment"
      #     git push
